Feature/paho mqtt
wirenboard/wb-common pull request #5
Opened 2022-08-15 05:58 UTC by vdromanov

в процессе ковыряний с тест-сьютом (помогал дружить его с py3), выяснилось, что wb_common переехал на py3 в своё время не очень хорошо

теперь wbmqtt: paho/mosquitto, py2/3 совместимо

2022-08-16 09:45 UTC, webconn commented on debian/control
> +Depends: python, ${misc:Depends}, python-six, busybox, python-mosquitto
Давай совсем уберём зависимость от mosquitto, раз так? wb-common может быть разных версий в разных дистрибутивах

2022-08-16 10:59 UTC, vdromanov commented on debian/control
> +Depends: python, ${misc:Depends}, python-six, busybox, python-mosquitto
готово

2022-08-18 13:24 UTC, webconn requested changes

2022-08-18 13:24 UTC, webconn commented on debian/control
> +Depends: python3, ${misc:Depends}, python3-six, busybox, python3-mosquitto | python3-paho-mqtt
Тут осталось `mosquitto`, для py3 точно можно выпиливать.

2022-08-18 13:24 UTC, webconn commented on debian/control
> +Depends: python, ${misc:Depends}, python-six, busybox, python-mosquitto
Так зависимость осталась в python3-пакете и в исходниках

2022-08-18 13:24 UTC, webconn commented on wb_common/wbmqtt.py
> +    import mosquitto as mqtt
Я на полном серьёзе предлагаю mosquitto убирать отовсюду, и совместимость с py2 нам уже особо не нужна. Нам нет никакого смысла дальше тащить легаси. Для старых релизов останется версия с py2.

2022-11-09 10:52 UTC, vdromanov commented
кажется, неактуально
закрываю

2022-11-09 10:52 UTC, closed without merging